//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.11 at 12:02:10 PM IDT 
//

package EnigmaMachineFactory.JAXBGenerated;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the EnigmaMachineFactory.JAXBGenerated package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: EnigmaMachineFactory.JAXBGenerated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Dictionary }
     * 
     */
    public Dictionary createDictionary() {
        return new Dictionary();
    }

    /**
     * Create an instance of {@link EnigmaMachineFactory.JAXBGenerated.Reflectors }
     * 
     */
    public EnigmaMachineFactory.JAXBGenerated.Reflectors createReflectors() {
        return new Reflectors();
    }

    /**
     * Create an instance of {@link EnigmaMachineFactory.JAXBGenerated.Reflector }
     * 
     */
    public EnigmaMachineFactory.JAXBGenerated.Reflector createReflector() {
        return new Reflector();
    }

    /**
     * Create an instance of {@link EnigmaMachineFactory.JAXBGenerated.Reflect }
     * 
     */
    public EnigmaMachineFactory.JAXBGenerated.Reflect createReflect() {
        return new Reflect();
    }

    /**
     * Create an instance of {@link EnigmaMachineFactory.JAXBGenerated.Rotors }
     * 
     */
    public EnigmaMachineFactory.JAXBGenerated.Rotors createRotors() {
        return new Rotors();
    }

    /**
     * Create an instance of {@link Rotor }
     * 
     */
    public Rotor createRotor() {
        return new Rotor();
    }

    /**
     * Create an instance of {@link EnigmaMachineFactory.JAXBGenerated.Mapping }
     * 
     */
    public EnigmaMachineFactory.JAXBGenerated.Mapping createMapping() {
        return new Mapping();
    }

    /**
     * Create an instance of {@link Enigma }
     * 
     */
    public Enigma createEnigma() {
        return new Enigma();
    }

    /**
     * Create an instance of {@link EnigmaMachineFactory.JAXBGenerated.Machine }
     * 
     */
    public EnigmaMachineFactory.JAXBGenerated.Machine createMachine() {
        return new Machine();
    }

    /**
     * Create an instance of {@link Decipher }
     * 
     */
    public Decipher createDecipher() {
        return new Decipher();
    }

    /**
     * Create an instance of {@link Battlefield }
     * 
     */
    public Battlefield createBattlefield() {
        return new Battlefield();
    }

}
